# Generated by Django 5.0.7 on 2024-07-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_vue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='sit_fam',
            field=models.CharField(max_length=100),
        ),
    ]
